### ISSUE TITLE
Spaces are accepted although forbidden

### ISSUE THREAD

**Issue by ComiR** [flownative/neos-anchorlinks#2]
i.e. you can set the inspector field to `section id` which will result in `<div id="section id">` and the link will be `node://some-node-id#section id` which [obviously is not allowed](https://www.w3.org/TR/html5/dom.html#the-id-attribute).

**Comment by ComiR** [comment]
could simply be fixed with
```YAML
  properties:
    sectionId:
      validation:
        'TYPO3.Neos/Validation/RegularExpressionValidator':
          regularExpression : '^\S*$'
```
but probably showing the button only if valid and giving a more helpful message (like "no spaces allowed") would be better...
